### ISSUE TITLE
Vagrantfile improvement

### ISSUE THREAD

**Issue by chenzhiwei** [IBM/deploy-ibm-cloud-private#28]
Did you guys know this blog post?

You can download and check how I wrote the Vagrantfile.

https://www.ibm.com/developerworks/community/blogs/fe25b4ef-ea6a-4d86-a629-6f87ccf4649e/entry/Setting_up_an_IBM_Spectrum_Conductor_for_Containers_cluster_by_using_Vagrant?lang=en

**Comment by tpouyer** [comment]
I am aware of this Vagrantfile. The difference between the Vagrantfile you are referring to and the one hosted here is the number of vm’s Required to run it. This vagrantfile uses LXD to run the worker nodes inside the master node. This allows for the consumption of less resources in order to run ICP and still maintain a true multi-node deployment.

I wrote a medium post to explain how it works here:  https://medium.com/ibm-cloud/kubernetes-ibm-cloud-private-and-vagrant-oh-my-cedc0758036f?source=linkShare-b01e9f23499-1508847523

The post does a better job explaining this Vagrantfile’s setup than I can in this comment.

**Comment by grdnrio** [comment]
Hey sorry to comment on a closed issue, but just a thought on this.

I totally understand the LXC decision as it means you don't need a 32GB RAM workstation to run this! :)

The only issue with this is if you want to alter the infrastructure. For example, I'd like to add additional block devices to the workers so that can I test a Portworx installation. Are there any plans to spin this out into a VM based deployment?
